Repository AY2021S2-CS2113T-W09-2/tp, pull requests merged in 2021-03, with the labels that each got.

#46 Storage
  .gitignore
  build.gradle
  src/main/java/seedu/igraduate/IGraduate.java
  src/main/java/seedu/igraduate/Storage.java
  src/main/java/seedu/igraduate/Ui.java
  src/test/java/seedu/igraduate/IGraduateTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Enhancement

#91 Parser
  iGraduate-0.log
  src/main/java/seedu/igraduate/Parser.java
Labels: type.Task

#93 Modify code to cover pre-requisite functionalities edge case
  iGraduate-0.log
  src/main/java/seedu/igraduate/IGraduate.java
  src/main/java/seedu/igraduate/ModuleList.java
  src/main/java/seedu/igraduate/Parser.java
  src/main/java/seedu/igraduate/command/AddCommand.java
  src/main/java/seedu/igraduate/command/Command.java
  src/main/java/seedu/igraduate/command/DeleteCommand.java
  src/main/java/seedu/igraduate/exception/UnableToDeletePrereqModuleException.java
  src/main/java/seedu/igraduate/module/CoreModule.java
  src/main/java/seedu/igraduate/module/ElectiveModule.java
  src/main/java/seedu/igraduate/module/GeModule.java
  src/main/java/seedu/igraduate/module/MathModule.java
  src/main/java/seedu/igraduate/module/Module.java
  src/test/java/seedu/igraduate/ModuleListTest.java
  src/test/java/seedu/igraduate/command/AddCommandTest.java
  src/test/java/seedu/igraduate/command/DeleteCommandTest.java
  src/test/java/seedu/igraduate/command/DoneCommandTest.java
Labels: severity.High, type.Enhancement

#97 Add Edit function
  iGraduate-0.log
  src/main/java/seedu/igraduate/ModuleList.java
  src/main/java/seedu/igraduate/Parser.java
  src/main/java/seedu/igraduate/Ui.java
  src/main/java/seedu/igraduate/command/CapCommand.java
  src/main/java/seedu/igraduate/command/Command.java
  src/main/java/seedu/igraduate/command/UpdateCommand.java
  src/main/java/seedu/igraduate/exception/ModuleNotCompleteException.java
  src/main/java/seedu/igraduate/module/Module.java
  src/test/java/seedu/igraduate/ModuleListTest.java
  src/test/java/seedu/igraduate/command/AddCommandTest.java
  src/test/java/seedu/igraduate/command/DeleteCommandTest.java
  src/test/java/seedu/igraduate/command/DoneCommandTest.java
Labels: type.Enhancement

#99 Add JavaDocs for UpdateCommand and Parser
  src/main/java/seedu/igraduate/Parser.java
  src/main/java/seedu/igraduate/command/UpdateCommand.java
  src/main/java/seedu/igraduate/exception/ModuleNotCompleteException.java
Labels: documentation

#101 Fix issue #100 on unsaved information
  iGraduate-0.log
  src/main/java/seedu/igraduate/command/UpdateCommand.java
  src/main/java/seedu/igraduate/exception/ModuleNotCompleteException.java
Labels: severity.Medium, type.Bug

#103 Update user stories for v1.0 and v2.0
  docs/DeveloperGuide.md
Labels: documentation, help wanted, priority.High

#114 Add about and update value proposition
  docs/DeveloperGuide.md
Labels: documentation, type.Task

#122 Update developer guide
  docs/DeveloperGuide.md
Labels: documentation, priority.Medium, type.Task

#128 Update visibility of Storage function
  src/main/java/seedu/igraduate/storage/Storage.java
Labels: severity.Low

#131 Fix diagram bug
  docs/DeveloperGuide.md
Labels: documentation, severity.VeryLow, type.Bug

#140 Update user guide
  build.gradle
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/igraduate/logic/command/UpdateCommand.java
Labels: documentation

#144 Add unit tests and stubs for Parser
  src/main/java/seedu/igraduate/logic/Parser.java
  src/test/java/seedu/igraduate/ParserTest.java
  src/test/java/seedu/igraduate/stub/ParserStub.java
Labels: documentation, type.Task

#158 Add test cases for list command
  iGraduate-0.log.lck
  src/main/java/seedu/igraduate/IGraduate.java
  src/main/java/seedu/igraduate/logic/command/DoneCommand.java
  src/main/java/seedu/igraduate/logic/command/ListCommand.java
  src/main/java/seedu/igraduate/logic/command/UpdateCommand.java
  src/main/java/seedu/igraduate/logic/parser/Parser.java
  src/main/java/seedu/igraduate/model/list/ModuleList.java
  src/main/java/seedu/igraduate/ui/Ui.java
  src/test/java/seedu/igraduate/IGraduateTest.java
  src/test/java/seedu/igraduate/logic/ParserTest.java
  src/test/java/seedu/igraduate/logic/command/addcommand/AddCommandTest.java
  src/test/java/seedu/igraduate/logic/command/capcommand/CapCommandTest.java
  src/test/java/seedu/igraduate/logic/command/deletecommand/DeleteCommandIntegrationTest.java
  src/test/java/seedu/igraduate/logic/command/deletecommand/DeleteCommandUnitTest.java
  src/test/java/seedu/igraduate/logic/command/donecommand/DoneCommandTest.java
  src/test/java/seedu/igraduate/logic/command/exitcommand/ExitCommandTest.java
  src/test/java/seedu/igraduate/logic/command/listcommand/ListCommandTest.java
  src/test/java/seedu/igraduate/stub/ParserStub.java
Labels: priority.High, type.Task

#166 Add sequence diagram for AddCommand execution
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandSequenceDiagram.puml
  docs/images/AddCommandSequenceDiagram.png
  src/main/java/seedu/igraduate/logic/command/AddCommand.java
  src/main/java/seedu/igraduate/logic/command/CapCommand.java
  src/main/java/seedu/igraduate/logic/command/Command.java
  src/main/java/seedu/igraduate/logic/command/DoneCommand.java
  src/main/java/seedu/igraduate/logic/command/ExitCommand.java
  src/main/java/seedu/igraduate/logic/command/ListCommand.java
  src/main/java/seedu/igraduate/logic/command/UpdateCommand.java
  src/main/java/seedu/igraduate/logic/parser/Parser.java
  src/test/java/seedu/igraduate/logic/ParserTest.java
  src/test/java/seedu/igraduate/logic/command/UpdateCommandIntegrationTest.java
  src/test/java/seedu/igraduate/logic/command/deletecommand/DeleteCommandIntegrationTest.java
  src/test/java/seedu/igraduate/logic/command/donecommand/DoneCommandTest.java
  src/test/java/seedu/igraduate/logic/command/listcommand/ListCommandTest.java
  src/test/java/seedu/igraduate/stub/ParserStub.java
Labels: priority.High
